### ISSUE TITLE
`ParseFile` issues on Windows

### ISSUE THREAD

**Issue by AgnesToulet** [hmarr/codeowners#15]
Hello!

I noticed some issues running this library on Windows. Using `os.PathSeparator` [here](https://github.com/hmarr/codeowners/blob/main/match.go#L98) converts this path `/test/public` into this regexp `"\\Atest\\public\\.*\\z"` and this makes the `regexp.Compile` function return this error:
```
error parsing regexp: invalid character class range: `\pu`
```

This specific issue can be fixed by always using `/` as a separator but I don't know if it introduces errors in other functions.

**Comment by hmarr** [comment]
Hi, thanks for reporting this! I don't have a Windows computer to hand, but I got CI running on Windows in #16, and I think I've fixed the issue there.

Patterns should always use `/`, so the use of `os.PathSeparator` was an oversight there. For the paths to test against it's a little more subtle as you could feasibly be testing against paths on your local (Windows) filesystem _or_ e.g. paths in a repo you've fetched via the GitHub API, so I decided to normalise paths to using forward slashes to cover both cases. That adds and allocation when the normalisation does need to happen but shouldn't affect performance when normalisation isn't required.

Would you mind testing that branch and seeing if it fixes the issue for you?

**Comment by hmarr** [comment]
I just published v1.1.2, which includes that fix. Hopefully that did the job but let know if you're still having issues!
