### ISSUE TITLE
[BUG] Codeowner files with Giltlab nested teams not parsed properly

### ISSUE THREAD

**Issue by yuliazarkh** [hmarr/codeowners#21]
Example of codeowner file:
 
`* @group-x/subgroup-y/subgroup-z`

throws `invalid owner format '@group-x/subgroup-y/subgroup-z' at position 3 `

Gitlab docs:
https://docs.gitlab.com/ee/user/project/codeowners/#add-a-group-as-a-code-owner

**Comment by hmarr** [comment]
I just merged https://github.com/hmarr/codeowners/pull/19 — you should be able to get around this issue using `WithOwnerMatchers`
