### ISSUE TITLE
Feature Request: Given a path get codeowners

### ISSUE THREAD

**Issue by dan-kez** [hmarr/codeowners#3]
Hello!

This is a nice utility! It would be extremely useful to have a command line argument that given a file path to print the associated codeowners.

**Comment by hmarr** [comment]
Thanks! It should already work like that. E.g.:

```
$ codeowners package.json
package.json                                                            @example-user
```

See the [command line usage](https://github.com/hmarr/codeowners#command-line-usage) section of the README for details.

**Comment by hmarr** [comment]
(But let me know if I've misunderstood!)
